# fly.toml app configuration file generated for dry-pond-5837 on 2023-09-13T13:52:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-pond-5837"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
